export interface ParticipantData {
  name: string;
  church: string;
  active: boolean;
}

export const participants: ParticipantData[] = [
  { name: "Waris K", church: "DS", active: true },
  { name: "Taruli S", church: "DS", active: true },
  { name: "Semmy L", church: "DS", active: false },
  { name: "Tommy E N", church: "DS", active: true },
  { name: "Roofy M", church: "DS", active: false },
  { name: "Ode R", church: "DS", active: true },
  { name: "Yeldy T", church: "DS", active: true },
  { name: "Alfrits M", church: "DS", active: true },
  { name: "Robby Rengkung", church: "DS", active: true },
  { name: "Yohanes T", church: "DS", active: true },
  { name: "Roy M", church: "DS", active: true },
  { name: "Jannes", church: "Trinitas", active: true },
  { name: "Ropen Silitonga", church: "Agape", active: true },
  { name: "Ricky Sitompul", church: "Agape", active: false },
  { name: "Retob", church: "Agape", active: false },
  { name: "Rudy T", church: "Agape", active: false },
  { name: "Roby Luntungan", church: "Agape", active: false },
  { name: "Robert Aruan", church: "Agape", active: true },
  { name: "Adrian", church: "Agape", active: false },
  { name: "Dicky", church: "Agape", active: false },
  { name: "Kiki", church: "Agape", active: false },
  { name: "Maurits Nainggolan", church: "Agape", active: false },
  { name: "Maxi Pantow", church: "Agape", active: false },
  { name: "Richard R", church: "Agape", active: false },
  { name: "Max Lethulur", church: "Agape", active: false },
  { name: "Marvin", church: "Agape", active: false },
  { name: "Steidy Rey", church: "Agape", active: false },
  { name: "Jerry Karepowan", church: "Agape", active: false },
  { name: "Yon Igunau", church: "Agape", active: false },
  { name: "Steven Talakua", church: "Agape", active: false },
  { name: "Reinhard Samah", church: "Agape", active: false },
  { name: "Erni luntungan", church: "Agape", active: false },
  { name: "Meivi Worang", church: "Agape", active: false },
  { name: "Jeini Worang", church: "Paulus", active: false },
  { name: "Johnny Tawas", church: "Agape", active: false },
  { name: "Arthur Tenda", church: "MK", active: false },
  { name: "Femmy Surentu", church: "MK", active: false },
  { name: "Nando", church: "MK", active: false },
  { name: "Theo W Manari", church: "DS", active: true },
  { name: "Jemmi Wuri", church: "Horeb", active: true },
  { name: "Florentia", church: "MK", active: false },
  { name: "Sarlota", church: "MK", active: false },
  { name: "Maya Maramis", church: "MI", active: false },
  { name: "Ferry Ginting", church: "DS", active: true },
  { name: "Kladius Telussa", church: "DS", active: true },
  { name: "Kris Sanjaya", church: "DS", active: true },
  { name: "Daniel E P", church: "DS", active: false },
  { name: "Yohanes S", church: "BK", active: false },
  { name: "Lukas P", church: "BK", active: false },
  { name: "Fredy Y", church: "BK", active: false },
  { name: "Roland S", church: "BK", active: false },
  { name: "Indra K", church: "Cipeucang", active: false },
  { name: "A. Dethan", church: "Cipeucang", active: false },
  { name: "Jimmy Yoo", church: "Cipeucang", active: true },
  { name: "Ronald Pieter", church: "Cipeucang", active: true },
  { name: "Max", church: "Cipeucang", active: false },
  { name: "P.Hehanusa", church: "Cipeucang", active: true },
  { name: "Berlin H", church: "Cipeucang", active: true },
  { name: "Andre Siahaya", church: "Cipeucang", active: true },
  { name: "Sonny Sine", church: "Cipeucang", active: false },
  { name: "Ventje DK", church: "DK", active: true },
  { name: "Benny Palit", church: "Cipeucang", active: true },
  { name: "FOL", church: "MK", active: true },
  { name: "Boy Assa", church: "MK", active: false },
  { name: "Jane Emtamoile", church: "MK", active: false },
  { name: "Oktav", church: "MK", active: false },
  { name: "Ety Ngantung", church: "Jatipon", active: false },
  { name: "Roy", church: "Hosiana", active: false },
  { name: "Ade Persulessy", church: "Cipeucang", active: true },
  { name: "Roger P", church: "Cipeucang", active: true },
  { name: "Donny Wagiu", church: "Hosiana", active: false },
  { name: "Paul Awuy", church: "Hosiana", active: false },
  { name: "Frans Patty", church: "Hosiana", active: false },
  { name: "Niel Saya", church: "Hosiana", active: false },
  { name: "Christian P", church: "Hosiana", active: false },
  { name: "Stefanus J", church: "Hosiana", active: false },
  { name: "Ayub H", church: "Hosiana", active: false },
  { name: "Dommy", church: "Hosiana", active: false },
  { name: "Ondik", church: "Hosiana", active: false },
  { name: "Aser", church: "Hosiana", active: false },
  { name: "DQ", church: "Hosiana", active: false },
  { name: "Florus N", church: "DS", active: true },
  { name: "Wemrom", church: "DS", active: true },
  { name: "Arie Politon", church: "MK", active: false },
  { name: "Toto R", church: "DS", active: false },
  { name: "Rico H", church: "DS", active: false },
  { name: "Igo T", church: "DS", active: false },
  { name: "Jeriko wongkar", church: "Agape", active: false },
  { name: "Brury T", church: "DS", active: false },
  { name: "Edwin Marthen", church: "Galilea", active: false },
  { name: "Tommy RT", church: "GMIM", active: false },
  { name: "Melki", church: "Pelita", active: false },
  { name: "Jone", church: "Pelita", active: false },
  { name: "Pande", church: "Pelita", active: false },
  { name: "Koko", church: "Pelita", active: false },
  { name: "Early", church: "Pelita", active: false },
  { name: "Lilik", church: "Pelita", active: false },
  { name: "Rayendra", church: "DK", active: false },
  { name: "Waediono sir", church: "MK", active: true },
  { name: "Nicky", church: "Pelita", active: false },
  { name: "Silas Teri", church: "DS", active: true },
  { name: "Nus R", church: "DS", active: true },
  { name: "Jenny", church: "Paulus", active: false },
  { name: "Sammy", church: "Retas Karunia", active: false },
  { name: "Maya", church: "Retas Karunia", active: false },
];

// Church color mapping
export const churchColors: Record<string, { bg: string; text: string; border: string }> = {
  'DS': { bg: 'bg-blue-500/15', text: 'text-blue-400', border: 'border-blue-500/30' },
  'Agape': { bg: 'bg-emerald-500/15', text: 'text-emerald-400', border: 'border-emerald-500/30' },
  'Trinitas': { bg: 'bg-purple-500/15', text: 'text-purple-400', border: 'border-purple-500/30' },
  'MK': { bg: 'bg-amber-500/15', text: 'text-amber-400', border: 'border-amber-500/30' },
  'Horeb': { bg: 'bg-cyan-500/15', text: 'text-cyan-400', border: 'border-cyan-500/30' },
  'MI': { bg: 'bg-rose-500/15', text: 'text-rose-400', border: 'border-rose-500/30' },
  'BK': { bg: 'bg-indigo-500/15', text: 'text-indigo-400', border: 'border-indigo-500/30' },
  'Cipeucang': { bg: 'bg-teal-500/15', text: 'text-teal-400', border: 'border-teal-500/30' },
  'DK': { bg: 'bg-violet-500/15', text: 'text-violet-400', border: 'border-violet-500/30' },
  'Jatipon': { bg: 'bg-orange-500/15', text: 'text-orange-400', border: 'border-orange-500/30' },
  'Hosiana': { bg: 'bg-pink-500/15', text: 'text-pink-400', border: 'border-pink-500/30' },
  'Galilea': { bg: 'bg-lime-500/15', text: 'text-lime-400', border: 'border-lime-500/30' },
  'GMIM': { bg: 'bg-sky-500/15', text: 'text-sky-400', border: 'border-sky-500/30' },
  'Pelita': { bg: 'bg-fuchsia-500/15', text: 'text-fuchsia-400', border: 'border-fuchsia-500/30' },
  'Paulus': { bg: 'bg-slate-500/15', text: 'text-slate-400', border: 'border-slate-500/30' },
  'Retas Karunia': { bg: 'bg-yellow-500/15', text: 'text-yellow-400', border: 'border-yellow-500/30' },
};

export const defaultChurchColor = { bg: 'bg-gray-500/15', text: 'text-gray-400', border: 'border-gray-500/30' };
