export interface ParticipantData {
  name: string;
  team: string;
  active: boolean;
  tableNumber?: number;
}

export const participants: ParticipantData[] = [
  {
    name: "WARIS K.",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 1,
  },
  {
    name: "BRURY T",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 1,
  },
  {
    name: "JONE",
    team: "GPIB PELITA",
    active: true,
    tableNumber: 1,
  },
  {
    name: "WARDIYONO SIR",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 1,
  },
  {
    name: "JIMMY YOO",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 1,
  },
  {
    name: "TARULI S",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 2,
  },
  {
    name: "SILASTERI",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 2,
  },
  {
    name: "PANDE",
    team: "GPIB PELITA",
    active: true,
    tableNumber: 2,
  },
  {
    name: "YOSEPH SIHAYA",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 2,
  },
  {
    name: "RONALD P",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 2,
  },
  {
    name: "SAMUEL",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 3,
  },
  {
    name: "NUS R",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 3,
  },
  {
    name: "ROY R",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 3,
  },
  {
    name: "ROY RICARDO",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 3,
  },
  {
    name: "MAX RUMAMBY",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 3,
  },
  {
    name: "TOMMY E.N",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 4,
  },
  {
    name: "AGUS JACOB",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 4,
  },
  {
    name: "DONNY WAGIU",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 4,
  },
  {
    name: "JERRY T",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 4,
  },
  {
    name: "P. HEHANUSA",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 4,
  },
  {
    name: "ROOFY M",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 5,
  },
  {
    name: "IGO T",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 5,
  },
  {
    name: "PAUL AWUY",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 5,
  },
  {
    name: "JOHN MARLON",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 5,
  },
  {
    name: "BERLIN H",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 5,
  },
  {
    name: "ODE R",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 6,
  },
  {
    name: "AGUS LEBA",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 6,
  },
  {
    name: "FRANS PATTY",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 6,
  },
  {
    name: "HENGKY TUPAMAHU",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 6,
  },
  {
    name: "ANDRE SIAHAYA",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 6,
  },
  {
    name: "YELDY T",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 7,
  },
  {
    name: "TORO",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 7,
  },
  {
    name: "NIEL",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 7,
  },
  {
    name: "RAYENDRA",
    team: "GPIB DIAN KASIH",
    active: true,
    tableNumber: 7,
  },
  {
    name: "SONNY SINE",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 7,
  },
  {
    name: "ALFRITS M",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 8,
  },
  {
    name: "RETTOB",
    team: "GPIB AGAPE",
    active: true,
    tableNumber: 8,
  },
  {
    name: "CHRISTIAN P",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 8,
  },
  {
    name: "Pdt. SAERANG",
    team: "GPIB DIAN KASIH",
    active: true,
    tableNumber: 8,
  },
  {
    name: "ADE P",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 8,
  },
  {
    name: "ROBBY RENGKUNG",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 9,
  },
  {
    name: "RUDY T",
    team: "GPIB AGAPE",
    active: true,
    tableNumber: 9,
  },
  {
    name: "STEFANUS J",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 9,
  },
  {
    name: "FRANS L",
    team: "GPIB DIAN KASIH",
    active: true,
    tableNumber: 9,
  },
  {
    name: "ROGER P",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 9,
  },
  {
    name: "YOHANES T",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 10,
  },
  {
    name: "ROBERT ARUAN",
    team: "GPIB AGAPE",
    active: true,
    tableNumber: 10,
  },
  {
    name: "AYUB H",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 10,
  },
  {
    name: "VENTJE",
    team: "GPIB DIAN KASIH",
    active: true,
    tableNumber: 10,
  },
  {
    name: "JOUNES",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 10,
  },
  {
    name: "ROY M",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 11,
  },
  {
    name: "KIKI",
    team: "GPIB AGAPE",
    active: true,
    tableNumber: 11,
  },
  {
    name: "DOMMY",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 11,
  },
  {
    name: "BOY",
    team: "DANTIS 1",
    active: true,
    tableNumber: 11,
  },
  {
    name: "LUCKY",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 11,
  },
  {
    name: "THEO W. MANARI",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 12,
  },
  {
    name: "ROPEN SILITONGA",
    team: "GPIB AGAPE",
    active: true,
    tableNumber: 12,
  },
  {
    name: "ONDIK",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 12,
  },
  {
    name: "SAMUEL",
    team: "DANTIS 2",
    active: true,
    tableNumber: 12,
  },
  {
    name: "BENNY PALIT",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 12,
  },
  {
    name: "FERRY GINTING",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 13,
  },
  {
    name: "RICKY SITOMPUL",
    team: "GPIB AGAPE",
    active: true,
    tableNumber: 13,
  },
  {
    name: "ASER",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 13,
  },
  {
    name: "YOHANES S",
    team: "GPIB BAHTERA KASIH",
    active: true,
    tableNumber: 13,
  },
  {
    name: "HANNY de FRETES",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 13,
  },
  {
    name: "KLADIUS TELUSSA",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 14,
  },
  {
    name: "DICKY AGUW",
    team: "GPIB AGAPE",
    active: true,
    tableNumber: 14,
  },
  {
    name: "D.Q",
    team: "GPIB HOSIANA",
    active: true,
    tableNumber: 14,
  },
  {
    name: "LUKAS P",
    team: "GPIB BAHTERA KASIH",
    active: true,
    tableNumber: 14,
  },
  {
    name: "HENDRY T.",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 14,
  },
  {
    name: "KRIS SANJAYA",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 15,
  },
  {
    name: "MAXY PANTOW",
    team: "GPIB AGAPE",
    active: true,
    tableNumber: 15,
  },
  {
    name: "ARTHUR TENDA",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 15,
  },
  {
    name: "FREDDY Y",
    team: "GPIB BAHTERA KASIH",
    active: true,
    tableNumber: 15,
  },
  {
    name: "YUSTER",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 15,
  },
  {
    name: "DANIEL E. P",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 16,
  },
  {
    name: "MELKY",
    team: "GPIB PELITA",
    active: true,
    tableNumber: 16,
  },
  {
    name: "FEMMY SURENTU",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 16,
  },
  {
    name: "ROLAND S",
    team: "GPIB BAHTERA KASIH",
    active: true,
    tableNumber: 16,
  },
  {
    name: "JANNES",
    team: "GPIB TRINITAS",
    active: true,
    tableNumber: 16,
  },
  {
    name: "FLORUS N",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 17,
  },
  {
    name: "KOKO",
    team: "GPIB PELITA",
    active: true,
    tableNumber: 17,
  },
  {
    name: "NANDO",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 17,
  },
  {
    name: "ONNY",
    team: "GPIB BAHTERA KASIH",
    active: true,
    tableNumber: 17,
  },
  {
    name: "DELKY POLII",
    team: "GPIB TRINITAS",
    active: true,
    tableNumber: 17,
  },
  {
    name: "WEMROM",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 18,
  },
  {
    name: "LILIK",
    team: "GPIB PELITA",
    active: true,
    tableNumber: 18,
  },
  {
    name: "FLORENTIA",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 18,
  },
  {
    name: "SAMMY L",
    team: "GPIB BAHTERA KASIH",
    active: true,
    tableNumber: 18,
  },
  {
    name: "EDWIN MARTHEN",
    team: "GPIB GALILEA",
    active: true,
    tableNumber: 18,
  },
  {
    name: "TOTO R",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 19,
  },
  {
    name: "SETIO",
    team: "GPIB PELITA",
    active: true,
    tableNumber: 19,
  },
  {
    name: "SARLOTTA",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 19,
  },
  {
    name: "INDRA K",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 19,
  },
  {
    name: "TOMMY R.T",
    team: "GMIM",
    active: true,
    tableNumber: 19,
  },
  {
    name: "RICO H",
    team: "GPIB DAMAI SEJAHTERA",
    active: true,
    tableNumber: 20,
  },
  {
    name: "NICKY",
    team: "GPIB PELITA",
    active: true,
    tableNumber: 20,
  },
  {
    name: "FOL",
    team: "GPIB MENARA KASIH",
    active: true,
    tableNumber: 20,
  },
  {
    name: "A. DETHAN",
    team: "GPIB CIPEUCANG",
    active: true,
    tableNumber: 20,
  },
  {
    name: "JEMMI WURI",
    team: "GPIB HOREB",
    active: true,
    tableNumber: 20,
  },
];

// Team color mapping
export const teamColors: Record<
  string,
  { bg: string; text: string; border: string }
> = {
  "GPIB DAMAI SEJAHTERA": {
    bg: "bg-blue-500/15",
    text: "text-blue-400",
    border: "border-blue-500/30",
  },
  "GPIB AGAPE": {
    bg: "bg-emerald-500/15",
    text: "text-emerald-400",
    border: "border-emerald-500/30",
  },
  "GPIB TRINITAS": {
    bg: "bg-purple-500/15",
    text: "text-purple-400",
    border: "border-purple-500/30",
  },
  "GPIB MENARA KASIH": {
    bg: "bg-amber-500/15",
    text: "text-amber-400",
    border: "border-amber-500/30",
  },
  "GPIB HOREB": {
    bg: "bg-cyan-500/15",
    text: "text-cyan-400",
    border: "border-cyan-500/30",
  },
  "GPIB BAHTERA KASIH": {
    bg: "bg-indigo-500/15",
    text: "text-indigo-400",
    border: "border-indigo-500/30",
  },
  "GPIB CIPEUCANG": {
    bg: "bg-teal-500/15",
    text: "text-teal-400",
    border: "border-teal-500/30",
  },
  "GPIB DIAN KASIH": {
    bg: "bg-violet-500/15",
    text: "text-violet-400",
    border: "border-violet-500/30",
  },
  "GPIB HOSIANA": {
    bg: "bg-pink-500/15",
    text: "text-pink-400",
    border: "border-pink-500/30",
  },
  "GPIB GALILEA": {
    bg: "bg-lime-500/15",
    text: "text-lime-400",
    border: "border-lime-500/30",
  },
  GMIM: {
    bg: "bg-sky-500/15",
    text: "text-sky-400",
    border: "border-sky-500/30",
  },
  "GPIB PELITA": {
    bg: "bg-fuchsia-500/15",
    text: "text-fuchsia-400",
    border: "border-fuchsia-500/30",
  },
  "DANTIS 1": {
    bg: "bg-orange-500/15",
    text: "text-orange-400",
    border: "border-orange-500/30",
  },
  "DANTIS 2": {
    bg: "bg-rose-500/15",
    text: "text-rose-400",
    border: "border-rose-500/30",
  },
};

export const defaultTeamColor = {
  bg: "bg-gray-500/15",
  text: "text-gray-400",
  border: "border-gray-500/30",
};
